services:
  mysql:
    container_name: mysql
    build:
      context: ./../../..
      dockerfile: ./shop/docker/local/mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: kocham_biznes
      MYSQL_DATABASE: sklepik
    networks:
      - prestashop_network
    volumes:
      - .shop/dbdata:/var/lib/mysql
      - ./dbdump:/var/lib/dbdump
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 90:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=kocham_biznes
    networks:
      - prestashop_network
    depends_on:
      - mysql
  
  prestashop:
    container_name: prestashop
    build:
      context: ./../../..
<<<<<<< HEAD
      dockerfile: ./shop/docker/local/presta.dockerfile
=======
      dockerfile: ./shop/presta.dockerfile
>>>>>>> master
    volumes:
      - ./shop/back-src:/var/www/back-src
    depends_on:
      - mysql
    ports:
      - 19323:443
    environment:
      DB_SERVER: mysql
      DB_NAME: sklepik
      DB_USER: root
      DB_PASSWD: kocham_biznes
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_DOMAIN: localhost:19323
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: admin@admin.com
      ADMIN_PASSWD: admin
    networks:
      - prestashop_network

networks:
  prestashop_network:
