<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container48bzxol\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container48bzxol/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container48bzxol.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container48bzxol\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container48bzxol\appDevDebugProjectContainer([
    'container.build_hash' => '48bzxol',
    'container.build_id' => '9765b927',
    'container.build_time' => 1733070099,
], __DIR__.\DIRECTORY_SEPARATOR.'Container48bzxol');
