<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4rdh7q4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4rdh7q4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4rdh7q4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4rdh7q4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4rdh7q4\appDevDebugProjectContainer([
    'container.build_hash' => '4rdh7q4',
    'container.build_id' => 'f2da4a0c',
    'container.build_time' => 1733290762,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4rdh7q4');
